const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'tom',
    disposition: 'sleepy',
    imageUrl: 'https://i.ytimg.com/vi/O3NQzrkAhD4/maxresdefault.jpg',
    fullness: 85,
    favPose: 'yoga stuff',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat3',
    name: 'gina',
    disposition: 'nice',
    imageUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_0/f_auto,q_auto,w_1100/v1555172619/shape/mentalfloss/iStock-177369626_0.jpg',
    fullness: 94,
    favPose: 'sun',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'dan',
    disposition: 'extra rude',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/A_white_irish_goat.jpg/220px-A_white_irish_goat.jpg',
    fullness: 10,
    favPose: 'moon',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat5',
    name: 'sam',
    disposition: 'rude',
    imageUrl: 'https://goatyoga.com/wp-content/uploads/goat-yoga-goat-in-pink-tutu-with-unicorn-horn.jpg',
    fullness: 23,
    favPose: 'more yoga stuff',
    isFainting: true,
    color: 'white',
  },
];

export default goats;
